// ============================================================================
//  DATABASE STORICO — SERIE A
// ----------------------------------------------------------------------------
//  Ogni voce è una "squadra-stagione" iconica.
//  Per ogni giocatore: nome, cognome, ruolo e overall (valutazione).
//
//  RUOLI:
//    P = Portiere
//    D = Difensore
//    C = Centrocampista
//    A = Attaccante
//
//  Gli overall sono calibrati sul valore del giocatore IN QUELLA stagione
//  (es. Del Piero 1994-95 è una giovane promessa, non ancora un top).
//  Scala: ~70 (riserva) → ~97 (fuoriclasse assoluto).
//
//  NB: questo è un dataset iniziale, accurato ma non esaustivo. È pensato
//  per essere ampliato facilmente aggiungendo altre squadre a questo array.
// ============================================================================

export const SQUADRE = [
  // --------------------------------------------------------------------------
  {
    id: "milan-1989-90",
    squadra: "Milan",
    anno: "1989-90",
    colore: "#fb0a18",
    giocatori: [
      { nome: "Giovanni", cognome: "Galli", ruolo: "P", overall: 85 },
      { nome: "Andrea", cognome: "Pazzagli", ruolo: "P", overall: 74 },
      { nome: "Franco", cognome: "Baresi", ruolo: "D", overall: 92 },
      { nome: "Paolo", cognome: "Maldini", ruolo: "D", overall: 88 },
      { nome: "Mauro", cognome: "Tassotti", ruolo: "D", overall: 82 },
      { nome: "Alessandro", cognome: "Costacurta", ruolo: "D", overall: 83 },
      { nome: "Filippo", cognome: "Galli", ruolo: "D", overall: 79 },
      { nome: "Frank", cognome: "Rijkaard", ruolo: "C", overall: 90 },
      { nome: "Carlo", cognome: "Ancelotti", ruolo: "C", overall: 84 },
      { nome: "Roberto", cognome: "Donadoni", ruolo: "C", overall: 85 },
      { nome: "Alberigo", cognome: "Evani", ruolo: "C", overall: 79 },
      { nome: "Angelo", cognome: "Colombo", ruolo: "C", overall: 76 },
      { nome: "Marco", cognome: "van Basten", ruolo: "A", overall: 94 },
      { nome: "Ruud", cognome: "Gullit", ruolo: "A", overall: 92 },
      { nome: "Daniele", cognome: "Massaro", ruolo: "A", overall: 80 },
      { nome: "Pietro Paolo", cognome: "Virdis", ruolo: "A", overall: 78 },
    ],
  },
  // --------------------------------------------------------------------------
  {
    id: "milan-2003-04",
    squadra: "Milan",
    anno: "2003-04",
    colore: "#fb0a18",
    giocatori: [
      { nome: "Dida", cognome: "", ruolo: "P", overall: 85 },
      { nome: "Christian", cognome: "Abbiati", ruolo: "P", overall: 79 },
      { nome: "Paolo", cognome: "Maldini", ruolo: "D", overall: 87 },
      { nome: "Alessandro", cognome: "Nesta", ruolo: "D", overall: 88 },
      { nome: "Cafu", cognome: "", ruolo: "D", overall: 84 },
      { nome: "Jaap", cognome: "Stam", ruolo: "D", overall: 84 },
      { nome: "Kakha", cognome: "Kaladze", ruolo: "D", overall: 79 },
      { nome: "Alessandro", cognome: "Costacurta", ruolo: "D", overall: 78 },
      { nome: "Andrea", cognome: "Pirlo", ruolo: "C", overall: 87 },
      { nome: "Clarence", cognome: "Seedorf", ruolo: "C", overall: 86 },
      { nome: "Gennaro", cognome: "Gattuso", ruolo: "C", overall: 83 },
      { nome: "Manuel", cognome: "Rui Costa", ruolo: "C", overall: 84 },
      { nome: "Massimo", cognome: "Ambrosini", ruolo: "C", overall: 80 },
      { nome: "Andriy", cognome: "Shevchenko", ruolo: "A", overall: 92 },
      { nome: "Kaká", cognome: "", ruolo: "A", overall: 88 },
      { nome: "Filippo", cognome: "Inzaghi", ruolo: "A", overall: 84 },
      { nome: "Jon Dahl", cognome: "Tomasson", ruolo: "A", overall: 80 },
    ],
  },
  // --------------------------------------------------------------------------
  {
    id: "milan-2006-07",
    squadra: "Milan",
    anno: "2006-07",
    colore: "#fb0a18",
    giocatori: [
      { nome: "Dida", cognome: "", ruolo: "P", overall: 84 },
      { nome: "Zeljko", cognome: "Kalac", ruolo: "P", overall: 73 },
      { nome: "Paolo", cognome: "Maldini", ruolo: "D", overall: 85 },
      { nome: "Alessandro", cognome: "Nesta", ruolo: "D", overall: 88 },
      { nome: "Cafu", cognome: "", ruolo: "D", overall: 83 },
      { nome: "Marek", cognome: "Jankulovski", ruolo: "D", overall: 80 },
      { nome: "Massimo", cognome: "Oddo", ruolo: "D", overall: 80 },
      { nome: "Kakha", cognome: "Kaladze", ruolo: "D", overall: 79 },
      { nome: "Andrea", cognome: "Pirlo", ruolo: "C", overall: 89 },
      { nome: "Kaká", cognome: "", ruolo: "C", overall: 92 },
      { nome: "Clarence", cognome: "Seedorf", ruolo: "C", overall: 87 },
      { nome: "Gennaro", cognome: "Gattuso", ruolo: "C", overall: 84 },
      { nome: "Massimo", cognome: "Ambrosini", ruolo: "C", overall: 81 },
      { nome: "Filippo", cognome: "Inzaghi", ruolo: "A", overall: 84 },
      { nome: "Alberto", cognome: "Gilardino", ruolo: "A", overall: 82 },
      { nome: "Ricardo", cognome: "Oliveira", ruolo: "A", overall: 78 },
    ],
  },
  // --------------------------------------------------------------------------
  {
    id: "juventus-1985-86",
    squadra: "Juventus",
    anno: "1985-86",
    colore: "#111111",
    giocatori: [
      { nome: "Stefano", cognome: "Tacconi", ruolo: "P", overall: 82 },
      { nome: "Luciano", cognome: "Bodini", ruolo: "P", overall: 70 },
      { nome: "Gaetano", cognome: "Scirea", ruolo: "D", overall: 86 },
      { nome: "Antonio", cognome: "Cabrini", ruolo: "D", overall: 83 },
      { nome: "Sergio", cognome: "Brio", ruolo: "D", overall: 79 },
      { nome: "Luciano", cognome: "Favero", ruolo: "D", overall: 76 },
      { nome: "Nicola", cognome: "Caricola", ruolo: "D", overall: 73 },
      { nome: "Michel", cognome: "Platini", ruolo: "C", overall: 94 },
      { nome: "Marco", cognome: "Tardelli", ruolo: "C", overall: 84 },
      { nome: "Massimo", cognome: "Bonini", ruolo: "C", overall: 80 },
      { nome: "Lionello", cognome: "Manfredonia", ruolo: "C", overall: 78 },
      { nome: "Beniamino", cognome: "Vignola", ruolo: "C", overall: 76 },
      { nome: "Zbigniew", cognome: "Boniek", ruolo: "A", overall: 86 },
      { nome: "Michael", cognome: "Laudrup", ruolo: "A", overall: 82 },
      { nome: "Aldo", cognome: "Serena", ruolo: "A", overall: 80 },
      { nome: "Massimo", cognome: "Briaschi", ruolo: "A", overall: 77 },
    ],
  },
  // --------------------------------------------------------------------------
  {
    id: "juventus-1994-95",
    squadra: "Juventus",
    anno: "1994-95",
    colore: "#111111",
    giocatori: [
      { nome: "Angelo", cognome: "Peruzzi", ruolo: "P", overall: 86 },
      { nome: "Michelangelo", cognome: "Rampulla", ruolo: "P", overall: 72 },
      { nome: "Ciro", cognome: "Ferrara", ruolo: "D", overall: 84 },
      { nome: "Pietro", cognome: "Vierchowod", ruolo: "D", overall: 82 },
      { nome: "Moreno", cognome: "Torricelli", ruolo: "D", overall: 78 },
      { nome: "Sergio", cognome: "Porrini", ruolo: "D", overall: 77 },
      { nome: "Luca", cognome: "Fusi", ruolo: "D", overall: 75 },
      { nome: "Antonio", cognome: "Conte", ruolo: "C", overall: 82 },
      { nome: "Didier", cognome: "Deschamps", ruolo: "C", overall: 84 },
      { nome: "Paulo", cognome: "Sousa", ruolo: "C", overall: 84 },
      { nome: "Angelo", cognome: "Di Livio", ruolo: "C", overall: 78 },
      { nome: "Andrea", cognome: "Fortunato", ruolo: "C", overall: 76 },
      { nome: "Alessio", cognome: "Tacchinardi", ruolo: "C", overall: 73 },
      { nome: "Roberto", cognome: "Baggio", ruolo: "A", overall: 91 },
      { nome: "Gianluca", cognome: "Vialli", ruolo: "A", overall: 88 },
      { nome: "Fabrizio", cognome: "Ravanelli", ruolo: "A", overall: 84 },
      { nome: "Alessandro", cognome: "Del Piero", ruolo: "A", overall: 80 },
    ],
  },
  // --------------------------------------------------------------------------
  {
    id: "juventus-2002-03",
    squadra: "Juventus",
    anno: "2002-03",
    colore: "#111111",
    giocatori: [
      { nome: "Gianluigi", cognome: "Buffon", ruolo: "P", overall: 89 },
      { nome: "Antonio", cognome: "Chimenti", ruolo: "P", overall: 70 },
      { nome: "Lilian", cognome: "Thuram", ruolo: "D", overall: 87 },
      { nome: "Paolo", cognome: "Montero", ruolo: "D", overall: 83 },
      { nome: "Gianluca", cognome: "Zambrotta", ruolo: "D", overall: 84 },
      { nome: "Ciro", cognome: "Ferrara", ruolo: "D", overall: 82 },
      { nome: "Igor", cognome: "Tudor", ruolo: "D", overall: 80 },
      { nome: "Mark", cognome: "Iuliano", ruolo: "D", overall: 78 },
      { nome: "Pavel", cognome: "Nedvěd", ruolo: "C", overall: 89 },
      { nome: "Edgar", cognome: "Davids", ruolo: "C", overall: 85 },
      { nome: "Mauro", cognome: "Camoranesi", ruolo: "C", overall: 82 },
      { nome: "Alessio", cognome: "Tacchinardi", ruolo: "C", overall: 80 },
      { nome: "Antonio", cognome: "Conte", ruolo: "C", overall: 79 },
      { nome: "Alessandro", cognome: "Del Piero", ruolo: "A", overall: 88 },
      { nome: "David", cognome: "Trezeguet", ruolo: "A", overall: 86 },
      { nome: "Marcelo", cognome: "Salas", ruolo: "A", overall: 80 },
      { nome: "Marco", cognome: "Di Vaio", ruolo: "A", overall: 80 },
    ],
  },
  // --------------------------------------------------------------------------
  {
    id: "juventus-2017-18",
    squadra: "Juventus",
    anno: "2017-18",
    colore: "#111111",
    giocatori: [
      { nome: "Gianluigi", cognome: "Buffon", ruolo: "P", overall: 89 },
      { nome: "Wojciech", cognome: "Szczęsny", ruolo: "P", overall: 84 },
      { nome: "Giorgio", cognome: "Chiellini", ruolo: "D", overall: 89 },
      { nome: "Andrea", cognome: "Barzagli", ruolo: "D", overall: 84 },
      { nome: "Medhi", cognome: "Benatia", ruolo: "D", overall: 84 },
      { nome: "Alex", cognome: "Sandro", ruolo: "D", overall: 84 },
      { nome: "Mattia", cognome: "De Sciglio", ruolo: "D", overall: 80 },
      { nome: "Stephan", cognome: "Lichtsteiner", ruolo: "D", overall: 80 },
      { nome: "Miralem", cognome: "Pjanić", ruolo: "C", overall: 85 },
      { nome: "Sami", cognome: "Khedira", ruolo: "C", overall: 84 },
      { nome: "Blaise", cognome: "Matuidi", ruolo: "C", overall: 83 },
      { nome: "Claudio", cognome: "Marchisio", ruolo: "C", overall: 81 },
      { nome: "Rodrigo", cognome: "Bentancur", ruolo: "C", overall: 76 },
      { nome: "Paulo", cognome: "Dybala", ruolo: "A", overall: 88 },
      { nome: "Gonzalo", cognome: "Higuaín", ruolo: "A", overall: 88 },
      { nome: "Mario", cognome: "Mandžukić", ruolo: "A", overall: 84 },
      { nome: "Douglas", cognome: "Costa", ruolo: "A", overall: 84 },
    ],
  },
  // --------------------------------------------------------------------------
  {
    id: "inter-1997-98",
    squadra: "Inter",
    anno: "1997-98",
    colore: "#0b1f8f",
    giocatori: [
      { nome: "Gianluca", cognome: "Pagliuca", ruolo: "P", overall: 84 },
      { nome: "Fabrizio", cognome: "Fontana", ruolo: "P", overall: 70 },
      { nome: "Giuseppe", cognome: "Bergomi", ruolo: "D", overall: 82 },
      { nome: "Taribo", cognome: "West", ruolo: "D", overall: 79 },
      { nome: "Aron", cognome: "Winter", ruolo: "D", overall: 80 },
      { nome: "Francesco", cognome: "Colonnese", ruolo: "D", overall: 77 },
      { nome: "Salvatore", cognome: "Fresi", ruolo: "D", overall: 76 },
      { nome: "Fabio", cognome: "Galante", ruolo: "D", overall: 76 },
      { nome: "Javier", cognome: "Zanetti", ruolo: "C", overall: 86 },
      { nome: "Youri", cognome: "Djorkaeff", ruolo: "C", overall: 86 },
      { nome: "Diego", cognome: "Simeone", ruolo: "C", overall: 84 },
      { nome: "Benoît", cognome: "Cauet", ruolo: "C", overall: 78 },
      { nome: "Ronaldo", cognome: "", ruolo: "A", overall: 95 },
      { nome: "Iván", cognome: "Zamorano", ruolo: "A", overall: 84 },
      { nome: "Maurizio", cognome: "Ganz", ruolo: "A", overall: 76 },
      { nome: "Nicola", cognome: "Ventola", ruolo: "A", overall: 74 },
    ],
  },
  // --------------------------------------------------------------------------
  {
    id: "inter-2009-10",
    squadra: "Inter",
    anno: "2009-10",
    colore: "#0b1f8f",
    giocatori: [
      { nome: "Júlio", cognome: "César", ruolo: "P", overall: 88 },
      { nome: "Francesco", cognome: "Toldo", ruolo: "P", overall: 78 },
      { nome: "Maicon", cognome: "", ruolo: "D", overall: 87 },
      { nome: "Lúcio", cognome: "", ruolo: "D", overall: 85 },
      { nome: "Walter", cognome: "Samuel", ruolo: "D", overall: 84 },
      { nome: "Javier", cognome: "Zanetti", ruolo: "D", overall: 86 },
      { nome: "Cristian", cognome: "Chivu", ruolo: "D", overall: 80 },
      { nome: "Marco", cognome: "Materazzi", ruolo: "D", overall: 79 },
      { nome: "Wesley", cognome: "Sneijder", ruolo: "C", overall: 88 },
      { nome: "Esteban", cognome: "Cambiasso", ruolo: "C", overall: 85 },
      { nome: "Thiago", cognome: "Motta", ruolo: "C", overall: 82 },
      { nome: "Dejan", cognome: "Stanković", ruolo: "C", overall: 82 },
      { nome: "McDonald", cognome: "Mariga", ruolo: "C", overall: 74 },
      { nome: "Samuel", cognome: "Eto'o", ruolo: "A", overall: 90 },
      { nome: "Diego", cognome: "Milito", ruolo: "A", overall: 87 },
      { nome: "Goran", cognome: "Pandev", ruolo: "A", overall: 80 },
      { nome: "Mario", cognome: "Balotelli", ruolo: "A", overall: 79 },
    ],
  },
  // --------------------------------------------------------------------------
  {
    id: "inter-2020-21",
    squadra: "Inter",
    anno: "2020-21",
    colore: "#0b1f8f",
    giocatori: [
      { nome: "Samir", cognome: "Handanović", ruolo: "P", overall: 83 },
      { nome: "Ionuț", cognome: "Radu", ruolo: "P", overall: 71 },
      { nome: "Stefan", cognome: "de Vrij", ruolo: "D", overall: 85 },
      { nome: "Milan", cognome: "Škriniar", ruolo: "D", overall: 84 },
      { nome: "Alessandro", cognome: "Bastoni", ruolo: "D", overall: 83 },
      { nome: "Achraf", cognome: "Hakimi", ruolo: "D", overall: 84 },
      { nome: "Aleksandar", cognome: "Kolarov", ruolo: "D", overall: 78 },
      { nome: "Danilo", cognome: "D'Ambrosio", ruolo: "D", overall: 78 },
      { nome: "Nicolò", cognome: "Barella", ruolo: "C", overall: 85 },
      { nome: "Marcelo", cognome: "Brozović", ruolo: "C", overall: 84 },
      { nome: "Ivan", cognome: "Perišić", ruolo: "C", overall: 82 },
      { nome: "Christian", cognome: "Eriksen", ruolo: "C", overall: 83 },
      { nome: "Arturo", cognome: "Vidal", ruolo: "C", overall: 80 },
      { nome: "Romelu", cognome: "Lukaku", ruolo: "A", overall: 88 },
      { nome: "Lautaro", cognome: "Martínez", ruolo: "A", overall: 85 },
      { nome: "Alexis", cognome: "Sánchez", ruolo: "A", overall: 81 },
    ],
  },
  // --------------------------------------------------------------------------
  {
    id: "napoli-1986-87",
    squadra: "Napoli",
    anno: "1986-87",
    colore: "#12a0d7",
    giocatori: [
      { nome: "Claudio", cognome: "Garella", ruolo: "P", overall: 80 },
      { nome: "Raffaele", cognome: "Di Fusco", ruolo: "P", overall: 70 },
      { nome: "Ciro", cognome: "Ferrara", ruolo: "D", overall: 80 },
      { nome: "Alessandro", cognome: "Renica", ruolo: "D", overall: 79 },
      { nome: "Moreno", cognome: "Ferrario", ruolo: "D", overall: 76 },
      { nome: "Giovanni", cognome: "Francini", ruolo: "D", overall: 76 },
      { nome: "Tebaldo", cognome: "Bigliardi", ruolo: "D", overall: 73 },
      { nome: "Fernando", cognome: "De Napoli", ruolo: "C", overall: 81 },
      { nome: "Salvatore", cognome: "Bagni", ruolo: "C", overall: 80 },
      { nome: "Francesco", cognome: "Romano", ruolo: "C", overall: 76 },
      { nome: "Eraldo", cognome: "Pecci", ruolo: "C", overall: 76 },
      { nome: "Diego", cognome: "Maradona", ruolo: "A", overall: 97 },
      { nome: "Bruno", cognome: "Giordano", ruolo: "A", overall: 82 },
      { nome: "Andrea", cognome: "Carnevale", ruolo: "A", overall: 80 },
    ],
  },
  // --------------------------------------------------------------------------
  {
    id: "napoli-1989-90",
    squadra: "Napoli",
    anno: "1989-90",
    colore: "#12a0d7",
    giocatori: [
      { nome: "Giuliano", cognome: "Giuliani", ruolo: "P", overall: 79 },
      { nome: "Pino", cognome: "Taglialatela", ruolo: "P", overall: 71 },
      { nome: "Ciro", cognome: "Ferrara", ruolo: "D", overall: 83 },
      { nome: "Alessandro", cognome: "Renica", ruolo: "D", overall: 79 },
      { nome: "Giovanni", cognome: "Francini", ruolo: "D", overall: 77 },
      { nome: "Giancarlo", cognome: "Corradini", ruolo: "D", overall: 75 },
      { nome: "Tebaldo", cognome: "Bigliardi", ruolo: "D", overall: 73 },
      { nome: "Alemão", cognome: "", ruolo: "C", overall: 84 },
      { nome: "Fernando", cognome: "De Napoli", ruolo: "C", overall: 82 },
      { nome: "Massimo", cognome: "Crippa", ruolo: "C", overall: 79 },
      { nome: "Luca", cognome: "Fusi", ruolo: "C", overall: 76 },
      { nome: "Diego", cognome: "Maradona", ruolo: "A", overall: 96 },
      { nome: "Careca", cognome: "", ruolo: "A", overall: 89 },
      { nome: "Andrea", cognome: "Carnevale", ruolo: "A", overall: 80 },
      { nome: "Gianfranco", cognome: "Zola", ruolo: "A", overall: 76 },
    ],
  },
  // --------------------------------------------------------------------------
  {
    id: "napoli-2022-23",
    squadra: "Napoli",
    anno: "2022-23",
    colore: "#12a0d7",
    giocatori: [
      { nome: "Alex", cognome: "Meret", ruolo: "P", overall: 82 },
      { nome: "Pierluigi", cognome: "Gollini", ruolo: "P", overall: 73 },
      { nome: "Kim", cognome: "Min-jae", ruolo: "D", overall: 85 },
      { nome: "Giovanni", cognome: "Di Lorenzo", ruolo: "D", overall: 83 },
      { nome: "Amir", cognome: "Rrahmani", ruolo: "D", overall: 81 },
      { nome: "Mário", cognome: "Rui", ruolo: "D", overall: 79 },
      { nome: "Mathías", cognome: "Olivera", ruolo: "D", overall: 79 },
      { nome: "Juan", cognome: "Jesus", ruolo: "D", overall: 76 },
      { nome: "Stanislav", cognome: "Lobotka", ruolo: "C", overall: 84 },
      { nome: "Frank", cognome: "Anguissa", ruolo: "C", overall: 84 },
      { nome: "Piotr", cognome: "Zieliński", ruolo: "C", overall: 83 },
      { nome: "Eljif", cognome: "Elmas", ruolo: "C", overall: 78 },
      { nome: "Victor", cognome: "Osimhen", ruolo: "A", overall: 88 },
      { nome: "Khvicha", cognome: "Kvaratskhelia", ruolo: "A", overall: 87 },
      { nome: "Hirving", cognome: "Lozano", ruolo: "A", overall: 81 },
      { nome: "Matteo", cognome: "Politano", ruolo: "A", overall: 80 },
      { nome: "Giacomo", cognome: "Raspadori", ruolo: "A", overall: 79 },
    ],
  },
  // --------------------------------------------------------------------------
  {
    id: "roma-1982-83",
    squadra: "Roma",
    anno: "1982-83",
    colore: "#8e1b2e",
    giocatori: [
      { nome: "Franco", cognome: "Tancredi", ruolo: "P", overall: 80 },
      { nome: "Maurizio", cognome: "Tancredi", ruolo: "P", overall: 70 },
      { nome: "Pietro", cognome: "Vierchowod", ruolo: "D", overall: 81 },
      { nome: "Sebastiano", cognome: "Nela", ruolo: "D", overall: 78 },
      { nome: "Dario", cognome: "Bonetti", ruolo: "D", overall: 76 },
      { nome: "Michele", cognome: "Nappi", ruolo: "D", overall: 74 },
      { nome: "Ubaldo", cognome: "Righetti", ruolo: "D", overall: 74 },
      { nome: "Falcão", cognome: "", ruolo: "C", overall: 90 },
      { nome: "Bruno", cognome: "Conti", ruolo: "C", overall: 86 },
      { nome: "Agostino", cognome: "Di Bartolomei", ruolo: "C", overall: 82 },
      { nome: "Carlo", cognome: "Ancelotti", ruolo: "C", overall: 80 },
      { nome: "Odoacre", cognome: "Chierico", ruolo: "C", overall: 74 },
      { nome: "Roberto", cognome: "Pruzzo", ruolo: "A", overall: 84 },
      { nome: "Francesco", cognome: "Graziani", ruolo: "A", overall: 79 },
      { nome: "Maurizio", cognome: "Iorio", ruolo: "A", overall: 72 },
    ],
  },
  // --------------------------------------------------------------------------
  {
    id: "roma-2000-01",
    squadra: "Roma",
    anno: "2000-01",
    colore: "#8e1b2e",
    giocatori: [
      { nome: "Francesco", cognome: "Antonioli", ruolo: "P", overall: 81 },
      { nome: "Cristiano", cognome: "Lupatelli", ruolo: "P", overall: 72 },
      { nome: "Cafu", cognome: "", ruolo: "D", overall: 85 },
      { nome: "Walter", cognome: "Samuel", ruolo: "D", overall: 84 },
      { nome: "Aldair", cognome: "", ruolo: "D", overall: 83 },
      { nome: "Vincent", cognome: "Candela", ruolo: "D", overall: 82 },
      { nome: "Jonathan", cognome: "Zebina", ruolo: "D", overall: 78 },
      { nome: "Emerson", cognome: "", ruolo: "C", overall: 84 },
      { nome: "Damiano", cognome: "Tommasi", ruolo: "C", overall: 81 },
      { nome: "Hidetoshi", cognome: "Nakata", ruolo: "C", overall: 80 },
      { nome: "Cristiano", cognome: "Zanetti", ruolo: "C", overall: 79 },
      { nome: "Marcos", cognome: "Assunção", ruolo: "C", overall: 79 },
      { nome: "Francesco", cognome: "Totti", ruolo: "A", overall: 90 },
      { nome: "Gabriel", cognome: "Batistuta", ruolo: "A", overall: 89 },
      { nome: "Vincenzo", cognome: "Montella", ruolo: "A", overall: 84 },
      { nome: "Marco", cognome: "Delvecchio", ruolo: "A", overall: 80 },
    ],
  },
  // --------------------------------------------------------------------------
  {
    id: "lazio-1999-00",
    squadra: "Lazio",
    anno: "1999-00",
    colore: "#88c7eb",
    giocatori: [
      { nome: "Angelo", cognome: "Peruzzi", ruolo: "P", overall: 86 },
      { nome: "Luca", cognome: "Marchegiani", ruolo: "P", overall: 79 },
      { nome: "Alessandro", cognome: "Nesta", ruolo: "D", overall: 87 },
      { nome: "Siniša", cognome: "Mihajlović", ruolo: "D", overall: 84 },
      { nome: "Fernando", cognome: "Couto", ruolo: "D", overall: 82 },
      { nome: "Giuseppe", cognome: "Pancaro", ruolo: "D", overall: 80 },
      { nome: "Giuseppe", cognome: "Favalli", ruolo: "D", overall: 80 },
      { nome: "Paolo", cognome: "Negro", ruolo: "D", overall: 79 },
      { nome: "Juan Sebastián", cognome: "Verón", ruolo: "C", overall: 88 },
      { nome: "Pavel", cognome: "Nedvěd", ruolo: "C", overall: 87 },
      { nome: "Diego", cognome: "Simeone", ruolo: "C", overall: 83 },
      { nome: "Sérgio", cognome: "Conceição", ruolo: "C", overall: 82 },
      { nome: "Dejan", cognome: "Stanković", ruolo: "C", overall: 81 },
      { nome: "Marcelo", cognome: "Salas", ruolo: "A", overall: 84 },
      { nome: "Alen", cognome: "Bokšić", ruolo: "A", overall: 82 },
      { nome: "Roberto", cognome: "Mancini", ruolo: "A", overall: 80 },
      { nome: "Simone", cognome: "Inzaghi", ruolo: "A", overall: 79 },
    ],
  },
  // --------------------------------------------------------------------------
  {
    id: "sampdoria-1990-91",
    squadra: "Sampdoria",
    anno: "1990-91",
    colore: "#0a3d8f",
    giocatori: [
      { nome: "Gianluca", cognome: "Pagliuca", ruolo: "P", overall: 84 },
      { nome: "Giulio", cognome: "Nuciari", ruolo: "P", overall: 70 },
      { nome: "Pietro", cognome: "Vierchowod", ruolo: "D", overall: 84 },
      { nome: "Luca", cognome: "Pellegrini", ruolo: "D", overall: 78 },
      { nome: "Moreno", cognome: "Mannini", ruolo: "D", overall: 77 },
      { nome: "Marco", cognome: "Lanna", ruolo: "D", overall: 75 },
      { nome: "Amedeo", cognome: "Carboni", ruolo: "D", overall: 76 },
      { nome: "Toninho", cognome: "Cerezo", ruolo: "C", overall: 83 },
      { nome: "Attilio", cognome: "Lombardo", ruolo: "C", overall: 82 },
      { nome: "Srečko", cognome: "Katanec", ruolo: "C", overall: 79 },
      { nome: "Fausto", cognome: "Pari", ruolo: "C", overall: 76 },
      { nome: "Giovanni", cognome: "Invernizzi", ruolo: "C", overall: 74 },
      { nome: "Gianluca", cognome: "Vialli", ruolo: "A", overall: 88 },
      { nome: "Roberto", cognome: "Mancini", ruolo: "A", overall: 87 },
      { nome: "Marco", cognome: "Branca", ruolo: "A", overall: 76 },
    ],
  },
  // --------------------------------------------------------------------------
  {
    id: "parma-1998-99",
    squadra: "Parma",
    anno: "1998-99",
    colore: "#f6c800",
    giocatori: [
      { nome: "Gianluigi", cognome: "Buffon", ruolo: "P", overall: 86 },
      { nome: "Marco", cognome: "Ballotta", ruolo: "P", overall: 72 },
      { nome: "Lilian", cognome: "Thuram", ruolo: "D", overall: 86 },
      { nome: "Fabio", cognome: "Cannavaro", ruolo: "D", overall: 85 },
      { nome: "Néstor", cognome: "Sensini", ruolo: "D", overall: 81 },
      { nome: "Antonio", cognome: "Benarrivo", ruolo: "D", overall: 78 },
      { nome: "Roberto", cognome: "Mussi", ruolo: "D", overall: 76 },
      { nome: "Juan Sebastián", cognome: "Verón", ruolo: "C", overall: 86 },
      { nome: "Dino", cognome: "Baggio", ruolo: "C", overall: 82 },
      { nome: "Diego", cognome: "Fuser", ruolo: "C", overall: 81 },
      { nome: "Stefano", cognome: "Fiore", ruolo: "C", overall: 78 },
      { nome: "Alain", cognome: "Boghossian", ruolo: "C", overall: 78 },
      { nome: "Hernán", cognome: "Crespo", ruolo: "A", overall: 86 },
      { nome: "Enrico", cognome: "Chiesa", ruolo: "A", overall: 83 },
      { nome: "Abel", cognome: "Balbo", ruolo: "A", overall: 81 },
      { nome: "Marco", cognome: "Di Vaio", ruolo: "A", overall: 77 },
    ],
  },
  // --------------------------------------------------------------------------
  {
    id: "fiorentina-1998-99",
    squadra: "Fiorentina",
    anno: "1998-99",
    colore: "#7b2bbd",
    giocatori: [
      { nome: "Francesco", cognome: "Toldo", ruolo: "P", overall: 84 },
      { nome: "Gianmatteo", cognome: "Mareggini", ruolo: "P", overall: 70 },
      { nome: "Tomáš", cognome: "Řepka", ruolo: "D", overall: 79 },
      { nome: "Moreno", cognome: "Torricelli", ruolo: "D", overall: 78 },
      { nome: "Daniele", cognome: "Adani", ruolo: "D", overall: 76 },
      { nome: "Pasquale", cognome: "Padalino", ruolo: "D", overall: 75 },
      { nome: "Aldo", cognome: "Firicano", ruolo: "D", overall: 74 },
      { nome: "Rui", cognome: "Costa", ruolo: "C", overall: 88 },
      { nome: "Guillermo", cognome: "Amor", ruolo: "C", overall: 79 },
      { nome: "Angelo", cognome: "Di Livio", ruolo: "C", overall: 78 },
      { nome: "Christian", cognome: "Amoroso", ruolo: "C", overall: 75 },
      { nome: "Emiliano", cognome: "Bigica", ruolo: "C", overall: 72 },
      { nome: "Gabriel", cognome: "Batistuta", ruolo: "A", overall: 90 },
      { nome: "Edmundo", cognome: "", ruolo: "A", overall: 84 },
      { nome: "Luís", cognome: "Oliveira", ruolo: "A", overall: 78 },
    ],
  },
  // --------------------------------------------------------------------------
  {
    id: "verona-1984-85",
    squadra: "Hellas Verona",
    anno: "1984-85",
    colore: "#1b5e9b",
    giocatori: [
      { nome: "Claudio", cognome: "Garella", ruolo: "P", overall: 79 },
      { nome: "Giuliano", cognome: "Giuliani", ruolo: "P", overall: 71 },
      { nome: "Hans-Peter", cognome: "Briegel", ruolo: "D", overall: 82 },
      { nome: "Roberto", cognome: "Tricella", ruolo: "D", overall: 79 },
      { nome: "Luciano", cognome: "Marangon", ruolo: "D", overall: 75 },
      { nome: "Mauro", cognome: "Ferroni", ruolo: "D", overall: 74 },
      { nome: "Silvano", cognome: "Fontolan", ruolo: "D", overall: 73 },
      { nome: "Antonio", cognome: "Di Gennaro", ruolo: "C", overall: 80 },
      { nome: "Pietro", cognome: "Fanna", ruolo: "C", overall: 77 },
      { nome: "Domenico", cognome: "Volpati", ruolo: "C", overall: 75 },
      { nome: "Luciano", cognome: "Bruni", ruolo: "C", overall: 73 },
      { nome: "Sergio", cognome: "Sacchetti", ruolo: "C", overall: 72 },
      { nome: "Preben", cognome: "Elkjær", ruolo: "A", overall: 86 },
      { nome: "Giuseppe", cognome: "Galderisi", ruolo: "A", overall: 80 },
      { nome: "Domenico", cognome: "Turchetta", ruolo: "A", overall: 72 },
    ],
  },
];
