// Stemmi ufficiali dei club (da Wikimedia Commons, licenza libera) per le
// squadre storiche presenti nel database. Usati nel draft per mostrare lo
// stemma vero sopra la squadra estratta. Se un club non è mappato (rarissimo,
// club minori con poche stagioni) l'interfaccia ripiega sul pallino colorato.
export const STEMMI = {
  Fiorentina: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/ACF_Fiorentina_-_logo_%28Italy%2C_2022%29.svg/330px-ACF_Fiorentina_-_logo_%28Italy%2C_2022%29.svg.png",
  Inter: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/330px-FC_Internazionale_Milano_2021.svg.png",
  Lazio: "https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/S.S._Lazio_badge.svg/330px-S.S._Lazio_badge.svg.png",
  Milan: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Logo_of_AC_Milan.svg/330px-Logo_of_AC_Milan.svg.png",
  Roma: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f7/AS_Roma_logo_%282017%29.svg/330px-AS_Roma_logo_%282017%29.svg.png",
  Udinese: "https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/Udinese_Calcio_logo.svg/330px-Udinese_Calcio_logo.svg.png",
  Atalanta: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f2/Atalanta_BC_new_logo.svg/330px-Atalanta_BC_new_logo.svg.png",
  Juventus: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Juventus_FC_-_logo_black_%28Italy%2C_2020%29.svg/330px-Juventus_FC_-_logo_black_%28Italy%2C_2020%29.svg.png",
  Napoli: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/SSC_Napoli_2025_%28white_and_azure%29.svg/330px-SSC_Napoli_2025_%28white_and_azure%29.svg.png",
  Cagliari: "https://upload.wikimedia.org/wikipedia/en/thumb/6/61/Cagliari_Calcio_1920.svg/330px-Cagliari_Calcio_1920.svg.png",
  Genoa: "https://upload.wikimedia.org/wikipedia/en/thumb/2/2c/Genoa_CFC_crest.svg/330px-Genoa_CFC_crest.svg.png",
  Bologna: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Bologna_F.C._1909_logo.svg/330px-Bologna_F.C._1909_logo.svg.png",
  Torino: "https://upload.wikimedia.org/wikipedia/en/thumb/2/2e/Torino_FC_Logo.svg/330px-Torino_FC_Logo.svg.png",
  Sampdoria: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/U.C._Sampdoria_logo.svg/330px-U.C._Sampdoria_logo.svg.png",
  Parma: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Logo_Parma_Calcio_1913_%28adozione_2016%29.svg/330px-Logo_Parma_Calcio_1913_%28adozione_2016%29.svg.png",
  Chievo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f0/A.C._ChievoVerona_logo.svg/330px-A.C._ChievoVerona_logo.svg.png",
  Sassuolo: "https://upload.wikimedia.org/wikipedia/en/thumb/1/1c/US_Sassuolo_Calcio_logo.svg/330px-US_Sassuolo_Calcio_logo.svg.png",
  "Hellas Verona": "https://upload.wikimedia.org/wikipedia/en/thumb/9/92/Hellas_Verona_FC_logo_%282020%29.svg/330px-Hellas_Verona_FC_logo_%282020%29.svg.png",
  Empoli: "https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Empoli_FC_crest.svg/330px-Empoli_FC_crest.svg.png",
  Palermo: "https://upload.wikimedia.org/wikipedia/en/thumb/d/df/Palermo_Calcio_logo_%282019%29.svg/330px-Palermo_Calcio_logo_%282019%29.svg.png",
  Catania: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Logo_CATANIA_FC.svg/330px-Logo_CATANIA_FC.svg.png",
  Lecce: "https://upload.wikimedia.org/wikipedia/en/thumb/2/23/US_Lecce_crest.svg/330px-US_Lecce_crest.svg.png",
  Siena: "https://upload.wikimedia.org/wikipedia/en/thumb/6/62/Siena_FC_SSD_crest.svg/330px-Siena_FC_SSD_crest.svg.png",
  Livorno: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Livorno-Stemma_semplificato.svg/330px-Livorno-Stemma_semplificato.svg.png",
  Cesena: "https://upload.wikimedia.org/wikipedia/en/thumb/d/db/AC_Cesena.svg/330px-AC_Cesena.svg.png",
  Crotone: "https://upload.wikimedia.org/wikipedia/en/thumb/d/db/FC_Crotone_logo.svg/330px-FC_Crotone_logo.svg.png",
  Frosinone: "https://upload.wikimedia.org/wikipedia/en/thumb/0/0b/Frosinone_Calcio_logo.svg/330px-Frosinone_Calcio_logo.svg.png",
  Monza: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/AC_Monza_logo_%282021%29.svg/330px-AC_Monza_logo_%282021%29.svg.png",
  Reggina: "https://upload.wikimedia.org/wikipedia/en/thumb/c/cd/AS_Reggina_1914_crest.svg/330px-AS_Reggina_1914_crest.svg.png",
  Salernitana: "https://upload.wikimedia.org/wikipedia/en/thumb/8/85/US_Salernitana_1919_logo.svg/330px-US_Salernitana_1919_logo.svg.png",
  Spal: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d5/Ars_et_Labor_Ferrara_Calcio_crest.svg/330px-Ars_et_Labor_Ferrara_Calcio_crest.svg.png",
  Spezia: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6f/Spezia_Calcio_crest.svg/330px-Spezia_Calcio_crest.svg.png",
  Bari: "https://upload.wikimedia.org/wikipedia/en/thumb/8/85/SSC_Bari_crest.svg/330px-SSC_Bari_crest.svg.png",
  Benevento: "https://upload.wikimedia.org/wikipedia/en/thumb/6/61/Benevento_Calcio_logo.svg/330px-Benevento_Calcio_logo.svg.png",
  Brescia: "https://upload.wikimedia.org/wikipedia/en/thumb/1/17/Brescia_calcio_badge.svg/330px-Brescia_calcio_badge.svg.png",
  Como: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Calcio_Como_-_logo_%28Italy%2C_2019-%29.svg/330px-Calcio_Como_-_logo_%28Italy%2C_2019-%29.svg.png",
  Cremonese: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e1/US_Cremonese_logo.svg/330px-US_Cremonese_logo.svg.png",
  Pescara: "https://upload.wikimedia.org/wikipedia/en/thumb/0/06/Delfino_Pescara_logo.svg/330px-Delfino_Pescara_logo.svg.png",
  Venezia: "https://upload.wikimedia.org/wikipedia/en/thumb/3/39/Venezia_FC_crest.svg/330px-Venezia_FC_crest.svg.png",
  Ascoli: "https://upload.wikimedia.org/wikipedia/en/thumb/2/23/Ascoli_Calcio_1898_logo.svg/330px-Ascoli_Calcio_1898_logo.svg.png",
  Carpi: "https://upload.wikimedia.org/wikipedia/en/thumb/4/48/AC_Carpi_crest.svg/330px-AC_Carpi_crest.svg.png",
  Messina: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Logo_of_ACR_Messina.svg/330px-Logo_of_ACR_Messina.svg.png",
  Novara: "https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Novara_FC_crest.svg/330px-Novara_FC_crest.svg.png",
  Pisa: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Pisa_SC_crest.svg/330px-Pisa_SC_crest.svg.png",
};

export function stemmaSquadra(nomeClub) {
  return STEMMI[nomeClub] || null;
}
